# Generated by Django 2.2.3 on 2020-08-08 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ActivityPeriod',
        ),
    ]
