# Generated by Django 2.2.3 on 2020-08-08 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200808_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetailsmodel',
            name='id',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
