# Generated by Django 2.2.3 on 2020-08-08 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200808_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitymodel',
            name='end_time',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='activitymodel',
            name='start_time',
            field=models.CharField(max_length=30),
        ),
    ]
