# Generated by Django 2.2.3 on 2020-08-11 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200808_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitymodel',
            name='id',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
